### ISSUE TITLE
Touch Issue on new iOS 3d Touch

### ISSUE THREAD

**Issue by suu10mac** [brutella/chatheads#23]
Foremost thanks for this awesome work ....
Was working Perfect but seems issue on UITouch when it comes to devices with 3d Touch
On 3d Touch Devices when a touch is made,instead of 
- (void)draggableViewTouched:(CHDraggableView *)view 

it gets detected as drag move, and also noticed few changes on its CGPoint too... Can't get what's the issue on with these devices ???

**Comment by ducnmisbk** [comment]
@suu10mac  try this.

Replace CHDraggableView with these below.


[CHDraggableView.zip](https://github.com/brutella/chatheads/files/867422/CHDraggableView.zip)
