### ISSUE TITLE
Bug: Chat Head is selected and background is touchable and not dimmed

### ISSUE THREAD

**Issue by pedrovieira** [brutella/chatheads#4]
Here's the video preview to make it easier for you to see what's wrong: http://cl.ly/3B1s2r1j0f2O 
Steps to reproduce:
- Touch the Chat Head
- Drag the Chat Head a little bit to right/left and let go
- The background will be touchable and not dimmed

Thanks!

**Comment by michaelsayman** [comment]
For me at least, what I did was comment out the part where it removes the background from superview and where it makes it nil. Commenting out those two lines fixed it for me.

if (finished) {
           // [_backgroundView removeFromSuperview];
           // _backgroundView = nil;
            completionBlock();
}

Update: Btw, this is located in the "Dragging" view.

**Comment by elfenlaid** [comment]
Also, if you drag notification screen(down swipe from status bar, widget with weather, dow jones and etc.) with ChatHead and then hide notifications screen the ChatHead would stay at the center of screen.

**Comment by brutella** [comment]
Should be fixed now by @elfenlaid
