### ISSUE TITLE
Out of view bounds ChatHead

### ISSUE THREAD

**Issue by elfenlaid** [brutella/chatheads#7]
User is able to drag chat head out of bounds. 
In case of top border it's all right, ChatHead only start in strange position, but if ChatHead was touched, then it return to right position. It would be great if ChatHead respects a down border too. 

![iOS Simulator Screen shot 29 Apr 2013 16 31 32](https://f.cloud.github.com/assets/765790/438646/2e089226-b0d1-11e2-9717-e3cca04a801a.png)
![iOS Simulator Screen shot 29 Apr 2013 16 31 27](https://f.cloud.github.com/assets/765790/438647/2e483a02-b0d1-11e2-88d8-57d5205ef50c.png)

**Comment by brutella** [comment]
Should be fixed now.
